version: '3.3'
services:
        mongo:
            image: 'mongo'
            container_name: 'mongo-region'
            restart: always
            ports:
               - 27017:27017
            environment:
                - MONGO_INITDB_ROOT_USERNAME=admin
                - MONGO_INITDB_ROOT_PASSWORD=xxx111
                - MONGO_INITDB_DATABASE=region
            volumes:
                - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
